### ISSUE TITLE
Missing keyword "bool" for System.Boolean

### ISSUE THREAD

**Issue by pmg23** [stakx/TypeNameFormatter#11]
In 1.0.0-beta, `typeof(bool).GetFormattedName() == "Boolean"`. For consistency with Int32 et al, it should be `"bool"`.

**Comment by stakx** [comment]
Hah! I had the nagging feeling I forgot something. :laugh:

Cheers for reporting this. Feel free to submit a PR. Otherwise I'll fix it during the weekend.
