### ISSUE TITLE
Support ValueTuple<...>

### ISSUE THREAD

**Issue by pmg23** [stakx/TypeNameFormatter#12]
In 1.0.0-beta, `typeof((short, uint)).GetFormattedName() == "ValueTuple<short, uint>"`. It would be nicer (more idiomatic C#) if this were to return `"(short, uint)"` (and similarly for ValueTuples of any arity).

**Comment by stakx** [comment]
Thanks for reporting this! I think you're right. And turning off this transform should be possible via an additional, dedicated formatting option. The idea is that calling the two methods without any specific options should always return in the most compact, idiomatic representation.

I'll look into this over the weekend.
