### ISSUE TITLE
Should generic type parameters be rendered by default or not?

### ISSUE THREAD

**Issue by stakx** [stakx/TypeNameFormatter#20]
Currently, generic type parameter names are by default omitted from the formatted name unless specifically requested via `TypeNameFormatOptions.GenericParameterNames`. I've come to question whether it would be better to include parameter names by default, and turn the option into `TypeNameFormatOptions.NoGenericParameterNames`.

Some background:

```csharp
class Some<T>
{
    public Some<T> Field;
}

var fieldType = typeof(Some<>).GetField("Field").FieldType;
Console.WriteLine(fieldType.GetFormattedName(TypeNameFormatOptions.Default));
// => Some<>
```

The rendered name `Some<>` is arguably wrong because `T` as used in the return type `Some<T>` is actually an argument, and the field type `Some<T>` is actually a constructed generic type, not a type definition. This isn't directly visible in the C# source, but it's apparent in IL:

```
.class private auto ansi beforefieldinit Some`1<T> extends [mscorlib]System.Object
{
    .field public class Some`1<!T> Field
    // ...
}
```

Note the difference between ``Some`1<T>`` (type name) vs. ``Some`1<!T>`` (field type).

Reflection cannot distinguish between these two things (see e.g. [here](https://github.com/dotnet/coreclr/blob/e7ad6110bfc1b888aceba9e0abbcbaae475517a8/src/System.Private.CoreLib/src/System/Reflection/Emit/ILGenerator.cs#L474-L476)), which means the library cannot figure out that it should never omit `T` in the field type.

Inverting the default formatting options (i.e. replacing `GenericParameterNames` with `NoGenericParameterNames`) would make it somewhat less probably that people stumble upon this inconsistency and think it's a bug in this library.

**Comment by stakx** [comment]
@pmg23, you've provided really valuable feedback in other issues so I'd appreciate your thoughts on this: Would *including* generic type parameter names (`Nullable<T>`) be a better default than excluding them by default (`Nullable<>`)?

**Comment by pmg23** [comment]
Hi

From a usability point-of-view, I think with or without the parameter name is fine, although in the unbound case `"Some<>"` is superior, for consistency with C# usage in `typeof` expressions.

How about this simpler case though:

```cs
class Foo<T>
{
    public T Field;
}
```

At present, `typeof(Foo<>).GetField("Field").FieldType.GetFormattedName() == ""`, which seems wrong. For comparison, `.Name == "T"`. This seems to me the only sensible option.

Assuming `Foo<T>.Field` renders as "T", for consistency your `Some<T>.Field` should become `"Some<T>"`. If it's much simpler for `typeof(Some<>)` to render as `"Some<T>"` as well, I think that's perfectly acceptable.

Regards
Matt

**Comment by stakx** [comment]
> At present, typeof(Foo<>).GetField("Field").FieldType.GetFormattedName() == "", which seems wrong. For comparison, .Name == "T". This seems to me the only sensible option.

:+1:, `"T"` is correct. This needs to be addressed.

> in the unbound case "Some<>" is superior, for consistency with C# usage in typeof expressions.

I tend to agree exactly, but...

> for consistency your Some<T>.Field should become "Some<T>".

... here lies the problem: Reflection doesn't allow us to determine whether this `T` is a type parameter or a type argument. As a parameter, it should be omitted, but as an argument, it should be included. So if we do generally omit type parameters in the unbound case, that has the unfortunate consequene of also removing the type argument `T` in this (bound) case.

**Comment by stakx** [comment]
I would've preferred to keep the previous behaviour, but I'd rather not risk users running into this problem (which isn't too unlikely to happen) and think it's a problem with the library. So given that both `Some<T>` and `Some<>` are equally correct, let's pick the one as the default that'll cause less bug reports that we could do nothing about.
