### ISSUE TITLE
Add ExcludeFromCodeCoverage or make class partial

### ISSUE THREAD

**Issue by kzu** [stakx/TypeNameFormatter#33]
Since this project already has all unit tests for this class, it should be excluded from code coverage analysis on referencing projects.

This can be achieved by either annotating the `TypeName` class with `[ExcludeFromCodeCoverage]` or by making the class partial so the consuming project can declare the partial class and add the attribute.

**Comment by stakx** [comment]
Merged and published version 1.0.1 on NuGet. Thanks for contributing!
