### ISSUE TITLE
Add Visual Basic as an alternate target language

### ISSUE THREAD

**Issue by stakx** [stakx/TypeNameFormatter#4]
This should be mostly straightforward. For example:

* generic types: use `(Of …)` instead of `<…>`
* array types: use `(…)` instead of `[]`
* by-ref types: use `ByRef ` (or nothing) instead of `ref ` (need to check)
* pointer types: throw an exception?

**Comment by pmg23** [comment]
Re pointer types, as discussed in #13, I think that it should return _something_ (on best-efforts basis) and never throw - so either invent some VB-esque syntax (e.g. "Pointer To T"), or fall back to C# syntax.

**Comment by stakx** [comment]
Closing this for the time being, I don't have too much interest in implementing this feature.

If anyone wants to do this, please raise your hand here ✋ .
