### ISSUE TITLE
Handle ValueTuple with 0 or 1 type parameters better

### ISSUE THREAD

**Issue by rcmdh** [stakx/TypeNameFormatter#41]
ValueTuples with arity 2 or more work fine by doing (T1,T2,T2), but for 0 - () and 1 - (T1) it doesn't work.  Please add support for returning 0 -> `ValueTuple,` 1 => `ValueTuple<T1>.`

**Comment by stakx** [comment]
> but for 0 - () and 1 - (T1) it doesn't work

I agree with the case for `ValueTuple` &mdash; that will be serialized as `"ValueTuple"`, not `"()"`.

But one-tuples seem to be serialized correctly: e.g. `ValueTuple<int>` will result in `"(int)"` as it should be... right?

**Comment by rcmdh** [comment]
Sadly (int) doesn't work, it needs to be ValueTuple<int>.  I assume it conflicts with casting syntax or something so they forbid it.

**Comment by stakx** [comment]
Sorry for the very long radio silence, @rcmdh. When you posted this issue, I was rather undecided about what would be the right thing to do. Then I left it lying around for too long and eventually forgot it. 😱

From a roundtripping perspective (and to fulfill the README's claim that this library produces C# formatting), this should be changed the way you suggested above.

From a "aesthetics" point of view, it would be nicer (more uniform) to keep `ValueTuple` formatted as `()` and `ValueTuple<T>` as `(T)` even if that isn't strictly valid C#. There is already a precedent where this library doesn't produce syntactically valid C# types (namely anonymous types such as that of `new { Name = "...", Count = ... }`). However, in that case, the alternative would have been equally invalid C#: `<>f__AnonymousType5<string, int>`.

So overall I tend to agree we should change this to correct C#.
