### ISSUE TITLE
Consider adding nullable annotations

### ISSUE THREAD

**Issue by kzu** [stakx/TypeNameFormatter#42]
When the consuming project has nullable enabled, the way this file is added to the compilation (perhaps? maybe it would always be this way anyway?) causes a bunch of nullable warnings.

For "generated" code (this might fit that definition, since it's added as source), it's recommended (found this while generating code with roslyn source generators) that the file itself declares its nullable context at the top, with :

```
#nullable enable
```

(or the corresponding `#nullable disable`).

So it could either be entirely annotated and `#nullable enable` or just a line at the top with `#nullable disable` :)

**Comment by stakx** [comment]
I am wondering if we really need two versions of the source file: one that is generally aware of nullable reference types (and that's also able to actually format them), and one that isn't (for backward compatibility).

It would be a shame to have to maintain two separate code files, but given the issue you discovered with `#nullable disable` not being understood by older toolchains, it's probably one of the only few options we have.

**Comment by kzu** [comment]
Yeah, it's quite annoying really :(

**Comment by stakx** [comment]
@kzu I've published a version 1.1.0 on NuGet that includes the `#nullable disable` from #44. Right now, upgrading the package apparently won't trigger a copy of the new file to your project's `obj/` folder, so you might have to manually delete `obj/` and do a package restore. I'm hoping to get around to fixing that soon, still wanted to get the updated package out there for you.

We could now change that to `#nullable enable` along with the necessary annotations in `TypeNameFormatter.Nullable.cs`. I'm finally seeing the warnings you were mentioning (they only appear in the preview version of VS 2019) so I should be able to fix those soon, too.
