### ISSUE TITLE
When using TypeNameFormatterInternal, configuration might cause diagnostics warnings/errors

### ISSUE THREAD

**Issue by kzu** [stakx/TypeNameFormatter#48]
Scenario:
- Someone sets TypeNameFormatterInternal=true
- Then via .editorconfig requires that default visibility is *not* specified (i.e. omit "internal" from class declarations, "private" from fields, etc.). This can be achieved with: `dotnet_style_require_accessibility_modifiers = omit_if_default:error`

Now the included TypeNameFormatter.cs will generate a build error (if set to error) due to:

```csharp
#if TYPENAMEFORMATTER_INTERNAL
    internal
#else
    public
#endif
```

The tricky thing here is that the rule can be set either way, so removing the `internal` might cause build errors for someone with the opposite setting (that all visibility modifiers are required).

This could be eliminated by adding a `SupressMessage` to all declared types: 

```csharp
[System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0040:Add accessibility modifiers")]
```

As a workaround, users can add the following to a *.editorconfig*:

```editorconfig
[TypeNameFormatter.cs]
dotnet_style_require_accessibility_modifiers = none
```

**Comment by stakx** [comment]
Thanks for figuring this out. :+1: `[SuppressMessage]` it shall be... seems better than forcing people to change their settings.
