### ISSUE TITLE
Hope to add TypeNameFormatOptions.NoGeneric

### ISSUE THREAD

**Issue by xlievo** [stakx/TypeNameFormatter#51]
```C#   
/// <summary>
///   Specifies that an open generic type's parameter names should be omitted.
///   <example>
///     For example, the open generic type <see cref="IEquatable{T}"/> is formatted as <c>"IEquatable&lt;T&gt;"</c> by default.
///     When this flag is specified, it will be formatted as <c>"IEquatable&lt;&gt;"</c>.
///   </example>
/// </summary>
NoGeneric = 64
```
Line 253
```C# 
if (IsSet(TypeNameFormatOptions.NoGeneric, options) == false && ownGenericTypeArgStartIndex < ownGenericTypeParamCount)
{
    //...
}
```
This is very effective for handling generic type merging. Thank you!
By the way, thank you for your contribution to Castle.Core.

**Comment by stakx** [comment]
I'm not sure what you're asking for here. The code shown suggests that `NoGeneric` would work exactly

**Comment by xlievo** [comment]
I have a special case ...
a: I need to get a generic name string without parameter types, and then splice a parameter type name to get a new generic name string.
b: Then hit the generic type dictionary generated in advance in "Source generator". The reason for this is related to MakeGenericType and AOT. That will be another story :)

However, to be honest, I hope this library can play a larger role in the processing of type names, such as more flexible processing methods for generics :)
If you have a different position, I understand, I will have to use the form of built-in source code, but it is not elegant!
Finally, maybe I was wrong or missed something.

**Comment by xlievo** [comment]
Maybe you are right. What I need is not a standard type format, so it is difficult... I may need to process it again.
It's time to close the issue until someone mentions it again.
thank you!
